services:
  # fullstack-db:
  #   image: mongo:8.0.9
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       order: start-first
  #       failure_action: rollback
  #       delay: 10s
  #     rollback_config:
  #       parallelism: 1
  #       order: start-first
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD
  #   volumes:
  #     - fullstack-db-vol:/data/db
  #   networks:
  #     - fullstack-network
  #   secrets:
  #     - MONGO_INITDB_ROOT_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD
  fullstack-redis:
    image: redis:8.0.0-alpine
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - redis-cli
        - "--raw"
        - incr
        - ping
    command: sh -c "up-redis.sh"
    volumes:
      - fullstack-redis-vol:/data
      - /home/github-user/up-redis.sh:/usr/local/bin/up-redis.sh
    networks:
      - fullstack-network
    secrets:
      - REDIS_PASSWORD
  fullstack-backend:
    image: kushal0107/fullstack-backend:build-a8d770f1edc3beed2dd91f0c7e7da81eaabcebfe
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - wget
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - http://localhost:8080/health
    environment:
      - PORT=8080
      - MONGO_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME_2
      - MONGO_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD_2
      - MONGO_HOST=testdb.u8uokfe.mongodb.net
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
      - REDIS_HOST=fullstack-redis
      - REDIS_PORT=6379
      - FRONTEND_URL=https://devops.kb-blogs.in
      - NODE_HOST="{{.Node.Hostname}}"
    networks:
      - fullstack-network
      - caddy-proxy_shared-net
    secrets:
      - MONGO_INITDB_ROOT_USERNAME_2
      - MONGO_INITDB_ROOT_PASSWORD_2
      - REDIS_PASSWORD
  fullstack-frontend:
    image: kushal0107/fullstack-frontend:build-a8d770f1edc3beed2dd91f0c7e7da81eaabcebfe
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:5173
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - VITE_BACKEND_URL=https://devops-api.kb-blogs.in
    networks:
      - fullstack-network
      - caddy-proxy_shared-net
networks:
  fullstack-network:
    driver: overlay
  caddy-proxy_shared-net:
    external: true
volumes:
  fullstack-db-vol: null
  fullstack-redis-vol: null
secrets:
  MONGO_INITDB_ROOT_USERNAME_2:
    external: true
  MONGO_INITDB_ROOT_PASSWORD_2:
    external: true
  REDIS_PASSWORD:
    external: true
