services:
  fullstack-db:
    image: mongo:8.0.9
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - fullstack-db-vol:/data/db
    networks:
      - fullstack-network
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  fullstack-redis:
    image: redis:8.0.0-alpine
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '--raw'
        - incr
        - ping
    command: sh -c "up-redis.sh"
    volumes:
      - fullstack-redis-vol:/data
      - /home/github-user/up-redis.sh:/usr/local/bin/up-redis.sh
    networks:
      - fullstack-network
    secrets:
      - REDIS_PASSWORD
  fullstack-backend:
    image: kushal0107/fullstack-backend:build-6d3ace34dc7c4470c63b7c172c21acaa3b292988
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - http://localhost:8080/health
    environment:
      - PORT=8080
      - MONGO_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME
      - MONGO_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD
      - MONGO_HOST=fullstack-db
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
      - REDIS_HOST=fullstack-redis
      - REDIS_PORT=6379
      - FRONTEND_URL=https://devops.kb-blogs.in
      - NODE_HOST="{{.Node.Hostname}}"
    networks:
      - fullstack-network
      - caddy-proxy_shared-net
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - REDIS_PASSWORD
  fullstack-frontend:
    image: kushal0107/fullstack-frontend:build-6d3ace34dc7c4470c63b7c172c21acaa3b292988
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:5173
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - VITE_BACKEND_URL=https://devops-api.kb-blogs.in
    networks:
      - fullstack-network
      - caddy-proxy_shared-net
networks:
  fullstack-network:
    driver: overlay
  caddy-proxy_shared-net:
    external: true
volumes:
  fullstack-db-vol: null
  fullstack-redis-vol: null
secrets:
  MONGO_INITDB_ROOT_USERNAME:
    external: true
  MONGO_INITDB_ROOT_PASSWORD:
    external: true
  REDIS_PASSWORD:
    external: true
