services:
  fullstack-db:
    image: mongo:8.0.9
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - fullstack-db-vol:/data/db
    networks:
      - fullstack-network
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  fullstack-redis:
    image: redis:8.0.0-alpine
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - redis-cli
        - "--raw"
        - incr
        - ping
    command: sh -c "up-redis.sh"
    volumes:
      - fullstack-redis-vol:/data
      - /home/github-user/up-redis.sh:/usr/local/bin/up-redis.sh
    networks:
      - fullstack-network
    secrets:
      - REDIS_PASSWORD
  fullstack-backend:
    image: kushal0107/fullstack-backend:build-8df0c90277bb347abc541d5af1e3b881d09c1ed3
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - wget
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - http://localhost:8080/health
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME
      - MONGO_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD
      - MONGO_HOST=fullstack-db
      - REDIS_PASSWORD_FILE=/run/secrets/REDIS_PASSWORD
      - REDIS_HOST=fullstack-redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://43.204.114.169:5173
      - NODE_HOST="{{.Node.Hostname}}"
    networks:
      - fullstack-network
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - REDIS_PASSWORD
  fullstack-frontend:
    image: kushal0107/fullstack-frontend:build-8df0c90277bb347abc541d5af1e3b881d09c1ed3
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:5173
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://43.204.114.169:8080
    networks:
      - fullstack-network
  caddy:
    image: caddy:2.6.2-alpine
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - fullstack-network
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
networks:
  fullstack-network:
    driver: overlay
volumes:
  fullstack-db-vol: null
  fullstack-redis-vol: null
  caddy_data: null
  caddy_config: null
secrets:
  MONGO_INITDB_ROOT_USERNAME:
    external: true
  MONGO_INITDB_ROOT_PASSWORD:
    external: true
  REDIS_PASSWORD:
    external: true
configs:
  Caddyfile:
    file: ./Caddyfile
