From node:22-slim AS builder

WORKDIR /app

COPY package*.json ./

# Ignore scripts to run
RUN npm ci --ignore-scripts 

COPY . .

RUN npm run build

RUN npm prune --omit=dev

FROM node:22-slim AS runner

WORKDIR /app

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder /app/wait-for-it.sh /usr/local/bin/wait-for-it.sh
COPY --from=builder /app/entrypoint.sh /usr/local/bin/entrypoint.sh

# Copy wait-for-it
# COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh

# Copy entrypoint
# COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Expose port
EXPOSE 8080

RUN useradd -m appuser
USER appuser

# Set entrypoint
ENTRYPOINT ["entrypoint.sh"]

# Start in prod mode
CMD ["node", "dist/index.js"]